<?php

namespace Domain\WorkshopName\Seeders;

use Domain\WorkshopName\Models\WorkshopName;
use Illuminate\Database\Seeder;

class WorkshopNameSeeder extends Seeder
{
    public function run(): void
    {
        $workshopsNames = [
            ['name' => 'Introduction to Mobile Device Security and Phishing attacks.'],
            ['name' => 'Introduction to AWS and its Application.'],
            ['name' => 'Object Oriented Analysis and Design'],
            ['name' => 'Virtual Reality and Augmented Reality'],
            ['name' => 'Block Chain Technology'],
            ['name' => 'Agile Software Project Management Tool'],
            ['name' => 'Bootstrap Framework'],
            ['name' => 'Introduction to Artificial Intelligence (AI)'],
            ['name' => 'Introduction to Python Django and Applications'],
            ['name' => 'Robotic Process Automation (RPA)'],
            ['name' => 'Entrepreneurship'],
            ['name' => 'JAVA Full Stack Web Development'],
            ['name' => 'Object Oriented Analysis and Design'],
            ['name' => 'Introduction to Cyber Security and its Applications'],
            ['name' => 'Introduction to Data Science and Applications'],
            ['name' => 'Principles and Applications of Artificial Neural Networks (ANN)'],
            ['name' => 'Introduction to Python Programming'],
            ['name' => 'DevOps using Cloud'],
            ['name' => 'Flutter Mobile Application Development'],
            ['name' => 'Internet of Things and Machine Learning'],

            ['name' => 'Introduction to Mobile Device Security and Phishing attacks.'],
            ['name' => 'Python & Data Science'],
            ['name' => 'Machine Learning & Artificial Intelligence'],
            ['name' => 'Web Development (HTML, CSS, JavaScript)'],
            ['name' => 'Cloud Computing (AWS/Azure)'],
            ['name' => 'Cybersecurity Essentials'],
            ['name' => 'Mobile App Development (Android/iOS)'],
            ['name' => 'DevOps & Continuous Integration'],
            ['name' => 'Ethical Hacking & Penetration Testing'],
            ['name' => 'Internet of Things (IoT)'],
            ['name' => 'Blockchain Technology'],
            ['name' => 'VLSI Design & Embedded Systems'],
            ['name' => 'Internet of Things (IoT) & Sensor Networks'],
            ['name' => 'Robotics & Automation'],
            ['name' => 'Digital Signal Processing (DSP)'],
            ['name' => 'Wireless Communication (5G)'],
            ['name' => 'PCB Design & Fabrication'],
            ['name' => 'Microcontroller Programming (Arduino, PIC, ARM)'],
            ['name' => 'Satellite Communication Basics'],
            ['name' => 'MATLAB for Signal Processing'],
            ['name' => 'Antenna Design'],
            ['name' => 'Precision Farming'],
            ['name' => 'Sustainable Agriculture Techniques'],
            ['name' => 'Soil Science & Fertilization'],
            ['name' => 'Crop Protection & Pest Management'],
            ['name' => 'Irrigation Techniques'],
            ['name' => 'Agricultural Biotechnology'],
            ['name' => 'Post-Harvest Technology'],
            ['name' => 'Agricultural Economics'],
            ['name' => 'Climate Change & Global Warming'],
            ['name' => 'Waste Management & Recycling'],
            ['name' => 'Water Conservation Techniques'],
            ['name' => 'Air Pollution Monitoring'],
            ['name' => 'Renewable Energy Systems'],
            ['name' => 'Biodiversity Conservation'],
            ['name' => 'Sustainable Agriculture'],
            ['name' => 'Urban Planning'],
            ['name' => 'Cryptography Introduction'],
            ['name' => 'Graph Theory & Network Models'],
            ['name' => 'Mathematical Modelling'],
            ['name' => 'Statistics with R/Python'],
            ['name' => 'Differential Equations Applications'],
            ['name' => 'Linear Algebra in Computer Science'],
            ['name' => 'Probability Theory'],
            ['name' => 'Game Theory & Decision Making'],
            ['name' => 'Organic Chemistry: Structure & Reactions'],
            ['name' => 'Analytical Chemistry Techniques'],
            ['name' => 'Green Chemistry Principles'],
            ['name' => 'Polymer Chemistry'],
            ['name' => 'Environmental Chemistry: Pollution Control'],
            ['name' => 'Industrial Chemistry'],
            ['name' => 'Nanotechnology in Chemistry'],
            ['name' => 'Drug Chemistry Basics'],
            ['name' => 'Quantum Mechanics & Applications'],
            ['name' => 'Basics of Electromagnetism'],
            ['name' => 'Optics & Photonics'],
            ['name' => 'Nanotechnology Introduction'],
            ['name' => 'Energy Physics: Solar & Wind Power'],
            ['name' => 'Electronics & Circuit Design'],
            ['name' => 'Thermodynamics Basics'],
            ['name' => 'Material Science'],
            ['name' => 'Genetic Engineering & CRISPR'],
            ['name' => 'Bioinformatics & Data Analysis'],
            ['name' => 'Molecular Biology Techniques (PCR, ELISA)'],
            ['name' => 'Environmental Biotechnology'],
            ['name' => 'Industrial Biotechnology'],
            ['name' => 'Nanotechnology in Biotechnology'],
            ['name' => 'Plant Tissue Culture'],
            ['name' => 'Microbial Biotechnology'],
            ['name' => 'Drug Discovery Process'],
            ['name' => 'Structural Design using STAAD Pro'],
            ['name' => 'Building Information Modeling (BIM)'],
            ['name' => 'Earthquake-Resistant Structure Design'],
            ['name' => 'Green Building Design'],
            ['name' => 'Advanced Surveying (Total Station, GIS)'],
            ['name' => 'Concrete Technology & Mix Design'],
            ['name' => 'Geotechnical Engineering'],
            ['name' => 'Construction Project Management'],
            ['name' => 'CAD/CAM using AutoCAD & SolidWorks'],
            ['name' => '3D Printing & Rapid Prototyping'],
            ['name' => 'Robotics & Automation in Manufacturing'],
            ['name' => 'Introduction to HVAC Systems'],
            ['name' => 'Finite Element Analysis (FEA)'],
            ['name' => 'CNC Machine Programming'],
            ['name' => 'Thermal Engineering & Heat Transfer'],
            ['name' => 'Mechatronics'],
            ['name' => 'Product Design & Development'],
            ['name' => 'Automobile Engineering (EVs)'],
            ['name' => 'Electrical Power Systems & Smart Grids'],
            ['name' => 'Renewable Energy Systems (Solar, Wind)'],
            ['name' => 'Electric Vehicles (EV) Technology'],
            ['name' => 'Power Electronics & Drives'],
            ['name' => 'PLC & SCADA for Industrial Automation'],
            ['name' => 'Circuit Design and Simulation'],
            ['name' => 'Energy Auditing & Management'],
            ['name' => 'Electric Motors & Drives'],
            ['name' => 'MATLAB for Electrical Systems'],
            ['name' => 'VLSI Design & Embedded Systems'],
            ['name' => 'Internet of Things (IoT) & Sensor Networks'],
            ['name' => 'Robotics & Automation'],
            ['name' => 'Digital Signal Processing (DSP)'],
            ['name' => 'Wireless Communication (5G)'],
            ['name' => 'PCB Design & Fabrication'],
            ['name' => 'Microcontroller Programming (Arduino, PIC, ARM)'],
            ['name' => 'Satellite Communication Basics'],
            ['name' => 'MATLAB for Signal Processing'],
            ['name' => 'Antenna Design'],
            ['name' => 'Python & Data Science'],
            ['name' => 'Machine Learning & Artificial Intelligence'],
            ['name' => 'Web Development (HTML, CSS, JavaScript)'],
            ['name' => 'Cloud Computing (AWS/Azure)'],
            ['name' => 'Cybersecurity Essentials'],
            ['name' => 'Mobile App Development (Android/iOS)'],
            ['name' => 'DevOps & Continuous Integration'],
            ['name' => 'Ethical Hacking & Penetration Testing'],
            ['name' => 'Internet of Things (IoT)'],
            ['name' => 'Blockchain Technology'],

            ['name' => 'Leadership & Team Building'],
            ['name' => 'Strategic Decision Making'],
            ['name' => 'Business Ethics & Corporate Governance'],
            ['name' => 'Digital Marketing & Social Media Strategies'],
            ['name' => 'Consumer Behavior Analysis'],
            ['name' => 'Branding & Brand Management'],
            ['name' => 'Financial Modeling & Valuation'],
            ['name' => 'Risk Management in Financial Institutions'],
            ['name' => 'Corporate Finance & Capital Budgeting'],
            ['name' => 'Recruitment Strategies & Talent Acquisition'],
            ['name' => 'Performance Management Systems'],
            ['name' => 'Employee Engagement & Retention'],
            ['name' => 'Lean Manufacturing & Six Sigma'],
            ['name' => 'Supply Chain Analytics & Optimization'],
            ['name' => 'Project Management Tools (e.g., Agile, Scrum)'],
            ['name' => 'Startup Ideation & Business Planning'],
            ['name' => 'Pitching & Investor Relations'],
            ['name' => 'Entrepreneurial Finance & Bootstrapping'],
            ['name' => 'Data Analytics & Visualization (Power BI, Tableau)'],
            ['name' => 'Artificial Intelligence & Machine Learning for Business'],
            ['name' => 'Cybersecurity & Risk Management'],
        ];

        collect($workshopsNames)->each(function ($workshopName) {
            WorkshopName::factory()->create([
                'name' => $workshopName['name'],
            ]);
        });
    }
}
