<?php

namespace Domain\Skill\Seeders;

use App\Models\User;
use Domain\Skill\Models\Skill;
use Domain\User\Models\UserDetails;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

class SkillSeeder extends Seeder
{
    public function run(): void
    {
        $skills = [
            'PHP',
            'Laravel',
            'JavaScript',
            'Node.js',
            'Flutter',
            'Python',
            'Java',
            'React',
            'Angular',
            'Vue.js',
            'HTML',
            'CSS',
            'SQL',
            'NoSQL',
            'AWS',
            'Azure',
            'Google Cloud',
            'Docker',
            'Kubernetes',
            'CI/CD',
            'Agile Methodology',
            'Scrum',
            'Project Management',
            'Git',
            'GitHub',
            'Bitbucket',
            'JIRA',
            'Trello',
            'Figma',
            'Adobe Photoshop',
            'Adobe Illustrator',
            'UX/UI Design',
            '3D Modeling',
            'Data Analysis',
            'Excel',
            'Tableau',
            'Power BI',
            'SEO',
            'Content Creation',
            'Digital Marketing',
            'Salesforce',
            'Customer Service',
            'CRM Management',
            'Microsoft Office',
            'Linux',
            'Windows Server',
            'Network Administration',
            'Cyber Security',
            'Ethical Hacking',
            'Mobile App Development',
            'iOS Development',
            'Android Development',
            'Machine Learning',
            'Artificial Intelligence',
            'Data Science',
            'Big Data',
            'Blockchain',
            'Cryptography',
            'Web Development',
            'RESTful APIs',
            'GraphQL',
            'Microservices',
            'DevOps',
            'Virtualization',
            'VMware',
            'Database Management',
            'MySQL',
            'PostgreSQL',
            'MongoDB',
            'Oracle',
            'Redis',
            'Elasticsearch',
            'C++',
            'C#',
            'Ruby',
            'Ruby on Rails',
            'Go',
            'Rust',
            'Swift',
            'Kotlin',
            'MATLAB',
            'SAS',
            'R Programming',
            'Financial Analysis',
            'Accounting',
            'Budget Management',
            'Taxation',
            'Compliance',
            'Supply Chain Management',
            'Logistics',
            'Quality Control',
            'Legal Research',
            'Contract Negotiation',
            'Content Strategy',
            'Technical Writing',
            'Copyrighting',
            'Social Media Marketing',
            'Brand Management',
            'Human Resources',
            'Talent Acquisition',
            'Employee Engagement',
            'Performance Management',
            'Compensation & Benefits',
            'Remote Work Management',
            'Time Management',
            'Virtual Collaboration',
            'Customer Relationship Management',
            'Lead Generation',
            'Sales',
            'Marketing',
            'Business Analysis',
            'Problem Solving',
            'Critical Thinking',
            'Leadership',
            'Teamwork',
            'Communication',
            'Creativity',
            'Adaptability',
            'Conflict Resolution',
            'Emotional Intelligence',
            'Multilingual',
            'Translation',
            'Remote Team Leadership',
            'Automation',
            'Embedded Systems',
            'Natural Language Processing',
            'Robotics',
            'Augmented Reality (AR)',
            'Virtual Reality (VR)',
            'Internet of Things (IoT)',
            'Game Development',
            '3D Printing',
            'Cloud Security',
            'IT Governance',
            'ITIL',
            'SAP',
            'Oracle ERP',
            'Business Intelligence',
            'Business Process Modeling',
            'Supply Chain Optimization',
            'Logistics Planning',
            'Data Mining',
            'Statistical Analysis',
            'Customer Experience Management',
            'Public Speaking',
            'Negotiation',
            'Training & Development',
            'Coaching & Mentoring',
            'Risk Management',
            'Change Management',
            'Corporate Strategy',
            'Strategic Planning',
            'Digital Transformation',
            'IT Project Management',
            'Health & Safety',
            'Environmental Sustainability',
            'Quality Assurance',
            'Lean Manufacturing',
            'Six Sigma',
            'Inventory Management',
            'Procurement',
            'Contract Management',
            'Vendor Management',
            'Legal Compliance',
            'Regulatory Affairs',
            'Event Planning',
            'Hospitality Management',
            'Customer Support',
            'Technical Support',
            'Software Testing',
            'QA Automation',
            'Load Testing',
            'Performance Testing',
            'User Acceptance Testing (UAT)',
            'Penetration Testing',
            'Incident Response',
            'Threat Analysis',
            'Disaster Recovery',
            'Backup Management',
            'Virtual Private Networks (VPN)',
            'Identity & Access Management (IAM)',
            'Endpoint Security',
            'Digital Forensics',
            'Malware Analysis',
            'System Administration',
            'Help Desk Support',
            'IT Asset Management',
            'ERP Implementation',
            'CRM Implementation',
            'Process Improvement',
            'Operational Efficiency',
            'Sales Forecasting',
            'Market Analysis',
            'Campaign Management',
            'Affiliate Marketing',
            'B2B Marketing',
            'B2C Marketing',
            'Lead Nurturing',
            'Customer Retention',
            'E-commerce',
            'Online Advertising',
            'Web Analytics',
            'Market Research',
            'Competitive Analysis',
            'Product Development',
            'Prototyping',
            'Testing & Evaluation',
            'User Research',
            'Customer Feedback Analysis',
            'Sales Strategy',
            'Direct Sales',
            'Channel Sales',
            'Partnership Development',
            'Franchise Management',
            'Investor Relations',
            'Fundraising',
            'Grant Writing',
            'Public Relations',
            'Corporate Communications',
            'Media Relations',
            'Internal Communications',
            'Crisis Management',
            'Event Marketing',
            'Corporate Social Responsibility (CSR)',
            'Diversity & Inclusion',
            'Employee Training',
            'Succession Planning',
            'Talent Management',
            'Organizational Development',
            'Employee Relations',
            'Workforce Planning',
            'Compensation Strategy',
            'Benefits Administration',
            'Performance Evaluation',
            'Employee Recognition',
            'Labor Relations',
            'Onboarding',
            'Offboarding',
            'Cultural Awareness',
            'Global Talent Management',
            'HR Analytics',
            'HRIS Management',
            'Payroll Management',
            'Remote Onboarding',
            'Remote Management',
            'Workforce Diversity',
            'Workforce Analytics',
        ];

        $user = User::factory()->create();

        $user->syncRoles('master');

        $permissions = Role::query()->where('name', 'master')->with('permissions')->get()->pluck('permissions')->flatten()->pluck('name')->toArray();

        $user->syncPermissions($permissions);

        UserDetails::factory()->create([
            'user_id' => $user->id,
            'full_name' => $user->name,
            'company_name' => $user->name,
            'company_mobile_number' => $user->phone ?? 'N/A', // Ensure phone is not null
            'company_email' => $user->email,
            'contact_person' => $user->name,
            'contact_person_email' => $user->email,
            'contact_person_phone' => $user->phone ?? 'N/A', // Ensure phone is not null
        ]);

        collect(array_unique($skills))->each(function ($skill) {
            Skill::factory()->create([
                'title' => $skill,
            ]);
        });
    }
}
