version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: alvinz97/dreamcarrer
    container_name: dreamcarrer
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network

  webserver:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: dreamcareer
      MYSQL_ROOT_PASSWORD: ;!Hy>JI2f9Ol
    ports:
      - "3306:3306"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
